from datetime import datetime

from pydantic import BaseModel


# Schema for creating a new user (input data from the client)
class UserCreate(BaseModel):
    # The user's email address
    email: str

    # The user's full name
    full_name: str


# Schema for reading/returning a user (output data sent to the client)
# Includes all fields, even those generated by the database (id, created_at)
class UserRead(BaseModel):
    # Unique database ID assigned automatically
    id: int

    # The user's email address
    email: str

    # The user's full name
    full_name: str

    # When the user record was created
    created_at: datetime

    class Config:
        # Allow Pydantic to read data from SQLAlchemy ORM objects
        from_attributes = True
